server:
    port: 8087

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/ead_authuser
        username: master
        password: 123
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show-sql: true